name: Top Off CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test engine
        run: swift test
